### ISSUE TITLE
latitude and latitudeInternalLabel Best Practice

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#15]
For 85 5th Ave, NY, NY, the internalLabel version of latlong is here:

![40 44_14_2_n_73 59_31_8_w_-_google_maps](https://cloud.githubusercontent.com/assets/1980690/13087619/d415afa8-d4b6-11e5-901d-921cc0395bf2.jpg)

For plain latlong, its here:
![40 44_14_7_n_73 59_33_3_w_-_google_maps](https://cloud.githubusercontent.com/assets/1980690/13087625/e425f20e-d4b6-11e5-9a18-96c2b4a0b2df.jpg)

What's the best practice/recommendation when geocoding NYC addresses?  When should one use the internalLabel version, and the plain latlong version?

**Comment by colinreilly** [comment]
There is no best practice as there are caveats with each. Both of these are Geosupport functions provided to increase the ability to get a valid response (i.e., hit). And it is always important to read the [documentation](http://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/upg.pdf).  

What you refer to as 'plain' coordinates, in Geosupport parlance is in essence a Function 1 call. This call returns the interpolated address within the administrative range of a blockface - see page 84 of the documentation. This does not ensure that the address is valid but merely that the house number is valid within the specified range. 

The label point coordinates are a function 1A call, which returns the label point (i.e., centroid) of the associated tax parcel. Function 1A returns a value only for valid addresses - see page 85 for a more detailed discussion. 

Geoclient docs:
internalLabelCoordinate
https://api.cityofnewyork.us/geoclient/v1/doc#item-internalLabelCoordinate

spatialCoordinates
https://api.cityofnewyork.us/geoclient/v1/doc#spatialCoordinates

Hope this helps.

**Comment by jqnatividad** [comment]
RTFM...  F for "Fine"... Thanks!
