### ISSUE TITLE
Tests are failing (SingleFieldSearchHandlerTest)

### ISSUE THREAD

**Issue by BenHizak** [CityOfNewYork/geoclient#27]
Test Summary
129 tests / 13 failures

Failed tests
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_addressWithTwoValidSimilarNames
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_addressWithZipAndNoBorough
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_blockfaceCrossStreetOneValidSimilarName
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_blockfaceCrossStreetTwoValidSimilarName
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_blockfaceExactMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_blockfaceOnStreetValidSimilarName
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_exactAddressMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_exactBblMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_exactBinMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_exactPlaceMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_intersectionExactMatch
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_intersectionWithCompassDirectionRequired
SingleFieldSearchHandlerTest. testFindLocationDefaultPolicy_intersectionWithOneValidSimilarName
Packages

Complete report:
[Build_Fail.zip](https://github.com/CityOfNewYork/geoclient/files/876228/Build_Fail.zip)

**Comment by jbn** [comment]
I'm having the same issue when trying to build on ubuntu:latest (via docker). 

Every find a resolution, @BeHiz?

**Comment by BeHiz** [comment]
I did get it up and running on another docker, but I don't know how to solve the problem.
You can reach me on 6178009148 later in the evening.

**Comment by jbn** [comment]
@BeHiz I appreciate the reply and offer! I'm going to work through it this morning and see what I find. I'll append to this log. (I'm on the West Coast, and keep odd hours.)

P.S. Bots do scan github for phone-number-like entries. I'd edit that out to prevent the deluge of "hi, let us help with your google listing," telemarketing calls.

**Comment by mlipper** [comment]
Feel free to get in touch with me directly if you get stuck. (FYI, I wrote this personal hackety-hack for a Dockerized Geosupport install for myself: https://github.com/mlipper/geosupport-docker)

**Comment by jbn** [comment]
Ah, excellent. I had to punt and give `delner/geoclient:16b` a pull, but I am still curious. I'll take a look at yours sometime this week. Thanks!

**Comment by mlipper** [comment]
Just to be clear: the image I referenced is for DCP's Geosupport itself and not Geoclient. I'm sure I'll build some basic Docker images for Geoclient too but not until I can clean up the documentation and outstanding issues to do a proper 2.0 release that installs and works intuitively on a non-containerized, "standard" Linux x86_64 host. Either way, get in touch and I can walk you through the basics.

**Comment by mlipper** [comment]
Fixed (approximately) in a1ab134358986f4730c9e24a55f8d2a22cc9ea79
