### ISSUE TITLE
Consider adding libpostal on to single-field search

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#30]
Right now, SFS goes thru 10 steps to parse a street per https://api.cityofnewyork.us/geoclient/v1/doc#section-1.3

It'd be awesome if [libpostal](https://github.com/openvenues/libpostal) is included in the algorithm, so Geoclient can almost behave like Google's Geocoding API :)

**Comment by mlipper** [comment]
Agreed, although I'd most likely create a simple plug-in API for geoclient-search and then implement this as a standalone project. The biggest blocker for me is time and the need to finish the basics for v2 first, but contributions are always welcome :-)

Can you provide a little more detail about the algorithm(s) you had in mind given what already exists?

Thanks!
Matt

**Comment by jqnatividad** [comment]
Originally, I was thinking it can be added between steps 2 & 3, but realized it may break apps that depend on the existing algorithm.

Perhaps, just add a new endpoint (libpostal-search?) that uses libpostal to normalize the address first, which then just passes the normalized address to the existing [address route](https://api.cityofnewyork.us/geoclient/v1/doc#section-1.2.1).

**Comment by mlipper** [comment]
Hey Joel! How's life? This is probably off your radar by now, but I'm in the process of closing out tickets in preparation for an upcoming Geoclient 2.0.0 release (finally).

I still like this suggestion but I also still feel that its outside of this project's scope: providing a developer-friendly way to geocode with DCP's Geosupport. I think that both libpostal and geoclient could be part of a composite geocoder that exists to improve search hits be being smart enough to work with multiple geocoding APIs depending on context.

I'm closing this ticket but feel free to rattle my cage if you think it warrants further discussion.

Thanks for your input!
