### ISSUE TITLE
Daily maintenance

### ISSUE THREAD

**Issue by jstrand73** [CityOfNewYork/geoclient#31]
Does the geoclient API undergo daily maintenance between 3am-4am?  We have an app that calls your service.  That app is continually monitored by WebSite Pulse to ensure the app is functioning.  WebSite Pulse errors for this app's monitor every day, at the step that calls the geoclient api.  Can you confirm that the api service is down daily for maintenance and what that maintenance window is?  Many thanks!!!

**Comment by mlipper** [comment]
Issue relates to hosting/production support and is out-of-scope for this source repo. Note that follow-up was done at the time of issue creation but errors were not found and were not observed thereafter.
