### ISSUE TITLE
clarify how to access API

### ISSUE THREAD

**Issue by afeld** [CityOfNewYork/geoclient#40]
I read through https://api.cityofnewyork.us/geoclient/v1/doc, and it wasn't clear to me:

- What the base URL for the API endpoints is
- How to get an application ID and key

It was only through a close read of https://developer.cityofnewyork.us/api/geoclient-api that I saw

> Access to the service requires registering for a free account on this website and requesting an access key.

Would be great to:

- Link from https://api.cityofnewyork.us/geoclient/v1/doc to https://developer.cityofnewyork.us/api/geoclient-api
- Elaborate on the steps for how to go from zero to making a live request

Thanks!

**Comment by ralphmapper** [comment]
I agree with you that there may be documentation but Google seems to not be able to find it easily.

But here's an example:

```
curl -v -X GET "https://api.nyc.gov/geo/geoclient/v1/search.json?input=26+broadway" -H "Ocp-Apim-Subscription-Key: XXX"
```

**Comment by julietsitron** [comment]
@ralphmapper thanks for the example! could you provide or point to similar in python?

**Comment by SteveScott** [comment]
It would be helpful if city planning released a python library to wrap these http requests.

**Comment by mlipper** [comment]
Hi "SteveScott",

Please be aware that the Geoclient project is actively maintained [here](https://github.com/mlipper/geoclient). This repo is now considered downstream.

[This thread](https://github.com/mlipper/geoclient/issues/5) shows an example using the "requests" library which wraps all the boilerplate HTTP wrangling. I can post the full example later today if you use that thread to request the complete file.

Also, I've heard of several python API's which either wrap Geoclient or connect directly to a local Geosupport installation.

If the above isn't what you had in mind, please [create a new issue here](https://github.com/mlipper/geoclient/issues).

Thanks,
Matt

**Comment by SteveScott** [comment]
I know how to use the requests library, but I would prefer a more Pythonic solution.

**Comment by mlipper** [comment]
Ok. If you decide to build something, please let me know: I'd interested to see what you had in mind. Thanks.
