### ISSUE TITLE
Reverse Geocoding

### ISSUE THREAD

**Issue by jqnatividad** [CityOfNewYork/geoclient#6]
Given location coordinates, give the normalized address.  Perhaps, can be done by integrating with other open-source projects? cc @riordan

**Comment by colinreilly** [comment]
I'm not clear as to what you are requesting. Geoclient provides access to Geosupport which in turn provides coordinates, normalized address, and other geographic coordinates for addresses, intersections, blocks and place names. If you would like to integrate Geoclient with other geocoders, the source is available for that or any other use.

**Comment by colinreilly** [comment]
Never mind my last comment, didn't see the subject. Reverse geocoding is certainly of interest but again that would be functionality required in Geosupport. Keep in mind that geoclient is only an API to Geosupport.

**Comment by mlipper** [comment]
Joel,

Having a robust reverse geocoder capable of working with "Geosupport-related data" is something that we would like to have internally as well. The data access methods, technologies, etc. are different than those used Geoclient, however, and if we were to build this, it would be in a separate project (ideally here on GH).

Thanks,

Matt

**Comment by riordan** [comment]
@colinreilly: From what it sounds like, the underlying system, Geosupport, doesn't support reverse  geocoding. Is that correct?

If so, it's kind of a bummer given how good Geoclient & Geosupport are at augmenting data about a place.

**Comment by chriswhong** [comment]
Geosupport can take a bin or a bbl as an input, so with another layer that produces BBLs/BINs from coordinates, it might be possible to set something like that up.

**Comment by colinreilly** [comment]
@riordan No it doesn't if you think of a reverse geocoder in the traditional sense (provide a coordinate pair and expect address, intersection, etc. response). It does as @Chris points out handle BIN and BBL but not lat/long or if you prefer long/lat as is usually expected. Definitely a need. IMHO and following the microservices approach, it would be best as a separate suite of services and not an extension to Geosupport. Yes, it's been on the radar but needs to be acted on.

**Comment by riordan** [comment]
Awesome  - thank you both for the clarification, @chriswhong, @colinreilly.

**Comment by chriswhong** [comment]
> it would be best as a separate suite of services and not an extension to Geosupport.

@colinreilly Challenge Accepted.

**Comment by colinreilly** [comment]
@chriswhong well it wasn't quite a challenge but by all means good luck! We've done some initial work on this. At least thinking about the problem and the difference cases. Let me know if you want to discuss/collaborate.
